/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.3/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.9.20"

    kotlin("kapt") version "1.9.20"

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven {
        url=uri("https://jitpack.io")
    }
}

dependencies {
    api("org.pf4j:pf4j:${project.properties["pf4jVersion"]}")
    api("com.badlogicgames.gdx:gdx:${project.properties["libgdxVersion"]}")
    kapt("org.pf4j:pf4j:${project.properties["pf4jVersion"]}")
    api(project(":runtime"))

    implementation("com.github.jamestkhan.mundus:commons:${project.properties["mundusVersion"]}")
    implementation("com.github.jamestkhan.mundus:plugin-api:${project.properties["mundusVersion"]}")
    implementation("com.github.jamestkhan.mundus:editor-commons:${project.properties["mundusVersion"]}")

    implementation("com.github.quickhull3d:quickhull3d:${project.properties["quickhull3dVersion"]}")
    implementation("com.massisframework.j3d:java3d-core:${project.properties["java3dCoreVersion"]}")

    testImplementation("org.junit.jupiter:junit-jupiter-engine:${project.properties["junit5Version"]}")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}

tasks.withType<Jar> {
    dependsOn(":runtime:jar")

    archiveFileName.set("ode4j-plugin.jar")

    // Otherwise you'll get a "No main manifest attribute" error
    manifest {
        attributes["Plugin-Class"]= "com.github.dgzt.mundus.plugin.ode4j.MundusOde4jEditorPlugin"
        attributes["Plugin-Id"] = "ode4j-plugin"
        attributes["Plugin-Provider"] = "Tibor Zsuro (Dgzt)"
        attributes["Plugin-Version"] = "0.0.1-SNAPSHOT"
    }

    // Include runtime in jar file
    val dependencies = configurations
        .runtimeClasspath
        .get()
        .filter {
            it.name.equals("runtime.jar") ||
            it.name.equals("gdx-ode4j-${project.properties["gdxOde4jVersion"]}.jar") ||
            it.name.equals("quickhull3d-${project.properties["quickhull3dVersion"]}.jar") ||
            it.name.equals("vecmath-${project.properties["java3dCoreVersion"]}.jar") ||
            it.name.equals("java3d-core-${project.properties["java3dCoreVersion"]}.jar")
        }
        .map(::zipTree)
    from(dependencies)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
